### ISSUE TITLE
Try to Deploy on Phone

### ISSUE THREAD

**Issue by brynamo** [brynamo/face2emoji#2]
#### We should have the developer accounts by now, so could someone try deploying to the phone?
- Need to make sure with the section of code for the camera uncommented)
- Need a different branch for working on the iPhone deployed version
- Don't need the other stuff to work (the emoji face) right now, so this doesn't need to wait on anything

**Comment by semerj** [comment]
Thanks for getting this set up. Can you also invite Jack (https://github.com/jchou)?

**Comment by brynamo** [comment]
Yeah, just got his github id (from him), sorry I didn't see this earlier

**Comment by brynamo** [comment]
@jchou I'm not sure if you've done this before but the Apple documentation isn't great... I found this (http://codewithchris.com/deploy-your-app-on-an-iphone/) quick tutorial on testing locally on an iOS device.

Could you possibly give it a try tonight and let us know how it works out?

**Comment by jchou** [comment]
Hey y'all, so... I actually don't have an iPhone, and I'm having trouble finding someone who would be willing to lend me their iPhone for a bit. Do you guys by any chance know if there's a way I can get my hands on a phone for testing? Alternatively, is there something else I should/can work on instead, like #1 or presentation stuff or something else? Thanks for your patience, finally got some time to check email today.

**Comment by semerj** [comment]
I can lend you an old iPhone 4s. The presentation part shouldn't be too difficult. We just need to actually ship something.

**Comment by semerj** [comment]
until then, @jchou can you work on https://github.com/brynamo/face2emoji/issues/1?

**Comment by jchou** [comment]
That would be great! And sure thing.

**Comment by semerj** [comment]
Awesome. Just make sure you get your Apply iOS dev stuff taken care of ASAP. I assume you got the email from John?

**Comment by jchou** [comment]
Yep, all taken care of, thanks.

**Comment by brynamo** [comment]
Ok cool, I will work on deploying to phone. Sorry @jchou I forgot you didn't have an iOS device.
